[project]
name = "hello-langgraph-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "ipython>=9.6.0,<10.0",
    "langchain[openai]>=1.0.3,<2.0",
    "langgraph>=1.0.2,<2.0",
    "python-dotenv>=1.2.1,<2.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/hello_langgraph"
]
